name: link checker

on:
  - push
  - pull_request

jobs:
  link-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - name: install hugo
        # Equivalent to peaceiris/actions-hugo@v3.2.1
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78
        with:
          hugo-version: '0.147.8'
      - name: build hugo
        run: hugo
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: yarn
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: yarn test
        run: yarn test
